"""Agent-facing endpoints: enrollment (HTTPS) + the live channel (WSS).

These routes never use session auth — agents authenticate with their own
credentials: a one-time enrollment token for POST /enroll, and
``Authorization: Bearer <device_id>:<device_secret>`` on the WebSocket.
"""

from __future__ import annotations

import shlex
import time

import structlog
from fastapi import (
    APIRouter,
    Depends,
    Header,
    HTTPException,
    Query,
    Request,
    WebSocket,
    WebSocketDisconnect,
    status,
)
from fastapi.responses import FileResponse, PlainTextResponse
from pydantic import BaseModel, Field

from .. import devices, job_secrets, jobs, metrics, patch_scan, patches, releases
from ..agents_ws import manager
from ..audit import record as audit_record
from ..config import Settings, get_settings
from ..fleet_ws import hub as fleet_hub
from ..ratelimit import SlidingWindowLimiter, client_ip

log = structlog.get_logger("agent_api")

router = APIRouter(prefix="/api/agent", tags=["agent"])

# Close codes on the agent socket. 4401 = credentials rejected — the agent
# treats it like any connection loss and retries with backoff, which also
# covers "device row deleted while agent still runs".
WS_CLOSE_UNAUTHORIZED = 4401


# --- Enrollment rate limiter --------------------------------------------------
# The token endpoints are the only unauthenticated surface besides the login,
# and an enrollment token is 24 hours of "may join the fleet". A token is
# secrets.token_urlsafe(24), so brute force is not the realistic threat — but
# an unthrottled endpoint that answers "valid / not valid" is a free oracle for
# a leaked-and-maybe-expired token, and free CPU for whoever wants it.
#
# Wider than the login limit because a genuine rollout can legitimately retry:
# a failed download, a re-run installer. Only failures count.
_enroll_limiter = SlidingWindowLimiter(max_events=20, window_s=300)


def reset_enroll_limiter_for_tests() -> None:
    _enroll_limiter.reset()


def _guard_enroll_rate(request: Request) -> str:
    ip = client_ip(request)
    if _enroll_limiter.limited(ip):
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Zu viele fehlgeschlagene Versuche — bitte später erneut probieren",
        )
    return ip


class EnrollRequest(BaseModel):
    token: str = Field(min_length=1, max_length=200)
    hostname: str = Field(min_length=1, max_length=255)
    owner_label: str = Field(default="", max_length=120)
    os: str = Field(default="", max_length=40)
    os_version: str = Field(default="", max_length=200)
    arch: str = Field(default="", max_length=20)
    agent_version: str = Field(default="", max_length=40)


@router.post("/enroll")
async def enroll(body: EnrollRequest, request: Request) -> dict:
    ip = _guard_enroll_rate(request)
    try:
        result = await devices.enroll_device(
            token=body.token,
            hostname=body.hostname,
            owner_label=body.owner_label,
            os=body.os,
            os_version=body.os_version,
            arch=body.arch,
            agent_version=body.agent_version,
        )
    except devices.EnrollmentError as e:
        _enroll_limiter.hit(ip)
        # 403 for all token failures; the message says why. No 404-vs-410
        # split — an attacker probing tokens learns nothing extra.
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(e)) from e
    await audit_record(
        "agent.enrolled",
        device_id=result["device_id"],
        hostname=body.hostname,
        os=body.os,
    )
    return result


@router.get("/download/{target}")
async def download_agent(target: str, authorization: str = Header(default="")) -> FileResponse:
    """Serve a signed agent binary for self-update. Device-authenticated —
    an agent downloads the target the server pointed it at, then verifies the
    signature against its pinned key before installing."""
    creds = _parse_bearer(authorization)
    device = await devices.authenticate_device(*creds) if creds else None
    if device is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid credentials")
    path = releases.binary_path(target)
    if path is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="unknown target")
    return FileResponse(path, media_type="application/octet-stream", filename=path.name)


# --- Setup bootstrap ---------------------------------------------------------
# One-liner installs from the dashboard: the script and the binary download
# authenticate with the (unconsumed) enrollment token, so the endpoints are
# public but useless without a token minted by an admin. The token is only
# burned by the actual enrollment at the end.

_SETUP_SH = r"""#!/usr/bin/env bash
# rxf-sys RMM agent bootstrap (generated by the server)
set -euo pipefail
SERVER=__SERVER__
TOKEN=__TOKEN__
LABEL=__LABEL__
[[ $EUID -eq 0 ]] || { echo "Bitte mit sudo/als root ausführen." >&2; exit 1; }
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$arch" in x86_64|amd64) arch=amd64;; aarch64|arm64) arch=arm64;; *) echo "nicht unterstützte Architektur: $arch" >&2; exit 1;; esac
# Ein laufender Dienst hält die Binary offen; curl -o scheitert dann mit
# "Text file busy". Erst stoppen — ein fehlender Dienst ist hier kein Fehler.
if [[ -x /usr/local/bin/rmm-agent ]]; then
  echo "==> stoppe vorhandenen Dienst"
  /usr/local/bin/rmm-agent stop >/dev/null 2>&1 || true
fi
echo "==> lade Agent ($os-$arch) von $SERVER"
# Token im Header statt in der URL — bleibt aus Proxy-/Access-Logs raus.
curl -fsSL -H "X-Enroll-Token: $TOKEN" "$SERVER/api/agent/setup/download/$os-$arch" -o /usr/local/bin/rmm-agent
chmod 0755 /usr/local/bin/rmm-agent
echo "==> enrolle Gerät"
/usr/local/bin/rmm-agent enroll --server "$SERVER" --token "$TOKEN" ${LABEL:+--label "$LABEL"}
echo "==> installiere + starte Dienst"
/usr/local/bin/rmm-agent install
/usr/local/bin/rmm-agent start
/usr/local/bin/rmm-agent version
echo "Fertig — das Gerät erscheint in Kürze im Dashboard."
"""

_SETUP_PS1 = r"""# rxf-sys RMM agent bootstrap (generated by the server)
$ErrorActionPreference = "Stop"
# Windows PowerShell 5.1 may still default to TLS 1.0/1.1, which a modern
# (Cloudflare-fronted) server rejects — force TLS 1.2 so the download works.
[Net.ServicePointManager]::SecurityProtocol = `
  [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
$Server = '__SERVER__'
$Token = '__TOKEN__'
$Label = '__LABEL__'
$Service = "rxf-rmm-agent"

$admin = ([Security.Principal.WindowsPrincipal] `
  [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
  [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $admin) {
  throw "Bitte in einer PowerShell mit Administratorrechten ausführen (Rechtsklick -> 'Als Administrator ausführen')."
}

$dir = Join-Path $env:ProgramFiles "rxf-rmm"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$exe = Join-Path $dir "rmm-agent.exe"

# A previous install keeps the .exe locked — stop the service first so the
# download can overwrite it (otherwise: 'file in use').
if (Get-Service -Name $Service -ErrorAction SilentlyContinue) {
  Write-Host "==> stoppe vorhandenen Dienst"
  Stop-Service -Name $Service -Force -ErrorAction SilentlyContinue
  Start-Sleep -Seconds 2
}

Write-Host "==> lade Agent (windows-amd64) von $Server"
try {
  # Token im Header statt in der URL — bleibt aus Proxy-/Access-Logs raus.
  Invoke-WebRequest -UseBasicParsing -Headers @{ 'X-Enroll-Token' = $Token } `
    -Uri "$Server/api/agent/setup/download/windows-amd64" -OutFile $exe
} catch {
  throw "Download fehlgeschlagen: $($_.Exception.Message) — Token noch gültig? Liegt ein signiertes Windows-Release auf dem Server (agent-releases/)?"
}

# Downloaded binaries carry the 'Mark of the Web'; strip it so SmartScreen/
# Defender does not silently block the service binary from starting.
Unblock-File -Path $exe -ErrorAction SilentlyContinue

# Sanity check: a real Windows binary starts with 'MZ'. An error page (bad
# token, no release) would land here as text and fail cryptically later.
$fs = [System.IO.File]::OpenRead($exe)
try { $b0 = $fs.ReadByte(); $b1 = $fs.ReadByte() } finally { $fs.Close() }
if ($b0 -ne 0x4D -or $b1 -ne 0x5A) {
  Remove-Item $exe -Force -ErrorAction SilentlyContinue
  throw "Der Download ist keine gültige .exe — vermutlich abgelaufenes Token oder kein Windows-Release hinterlegt."
}

Write-Host "==> enrolle Gerät"
$enrollArgs = @("enroll", "--server", $Server, "--token", $Token)
if ($Label -ne "") { $enrollArgs += @("--label", $Label) }
& $exe @enrollArgs
if ($LASTEXITCODE -ne 0) { throw "Enrollment fehlgeschlagen (Exit $LASTEXITCODE) — Token bereits verbraucht oder abgelaufen?" }

& $exe install
sc.exe failure $Service reset= 86400 actions= restart/3000/restart/3000/restart/3000 | Out-Null
& $exe start
& $exe version
Write-Host "Fertig — das Gerät erscheint in Kürze im Dashboard."
"""


def _public_base(request: Request) -> str:
    """Origin the CLIENT used, reconstructed behind the Cloudflare tunnel
    (X-Forwarded-Proto) so generated URLs point at https://rmm.rxf-sys.de,
    not the container-internal address.

    In production the public origin is always HTTPS — even when the
    forwarded header is missing (e.g. Caddy stripped it because
    TRUSTED_PROXY_CIDR isn't configured yet). An http:// base would break
    enrollment: the redirect to https turns the enroll POST into a GET
    (405)."""
    proto = request.headers.get("x-forwarded-proto") or request.url.scheme
    host = request.headers.get("host") or request.url.netloc
    if get_settings().app_env == "production":
        proto = "https"
    return f"{proto}://{host}"


async def _validate_setup_token(token: str, request: Request) -> None:
    ip = _guard_enroll_rate(request)
    if not token or not await devices.enrollment_token_valid(token):
        _enroll_limiter.hit(ip)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Enrollment-Token ungültig oder abgelaufen",
        )


@router.get("/setup/download/{target}")
async def setup_download(
    target: str,
    request: Request,
    token: str = Query(default=""),
    x_enroll_token: str = Header(default=""),
) -> FileResponse:
    """Binary download for first-time installs, authenticated with an
    unconsumed enrollment token (self-updates use /download/{target} with
    device credentials instead). The token travels in the X-Enroll-Token
    header (preferred — keeps it out of proxy/access logs); the query
    parameter remains as fallback for plain browser downloads."""
    await _validate_setup_token(x_enroll_token or token, request)
    path = releases.binary_path(target)
    if path is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Kein Agent-Release für dieses Ziel hinterlegt (agent-releases/ leer?)",
        )
    return FileResponse(path, media_type="application/octet-stream", filename=path.name)


@router.get("/setup/{platform}")
async def setup_script(
    platform: str,
    request: Request,
    token: str = Query(default=""),
    label: str = Query(default="", max_length=120),
    x_enroll_token: str = Header(default=""),
) -> PlainTextResponse:
    """Self-contained install script for `curl | sudo bash` (Linux/macOS)
    or `irm | iex` (Windows). Token preferred via X-Enroll-Token header
    (stays out of proxy logs); query fallback kept for hand-typed URLs."""
    token = x_enroll_token or token
    await _validate_setup_token(token, request)
    server = _public_base(request)
    if platform in ("linux", "darwin"):
        body = (
            _SETUP_SH.replace("__SERVER__", shlex.quote(server))
            .replace("__TOKEN__", shlex.quote(token))
            .replace("__LABEL__", shlex.quote(label))
        )
    elif platform == "windows":
        body = (
            _SETUP_PS1.replace("__SERVER__", server.replace("'", "''"))
            .replace("__TOKEN__", token.replace("'", "''"))
            .replace("__LABEL__", label.replace("'", "''"))
        )
    else:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="unbekannte Plattform")
    return PlainTextResponse(body, media_type="text/plain; charset=utf-8")


def _as_pct(value: object) -> float:
    """Clamp an untrusted agent-reported percentage into [0, 100]."""
    try:
        return max(0.0, min(100.0, float(value)))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return 0.0


def _parse_bearer(header: str) -> tuple[int, str] | None:
    """``Bearer <device_id>:<secret>`` → (device_id, secret), or None."""
    if not header.lower().startswith("bearer "):
        return None
    value = header.split(" ", 1)[1].strip()
    device_id_s, sep, secret = value.partition(":")
    if not sep or not device_id_s.isdigit() or not secret:
        return None
    return int(device_id_s), secret


async def _maybe_request_patch_scan(
    ws: WebSocket, device_id: int, last_scan_at: int, settings: Settings
) -> None:
    """Ask for an update scan if the device is past its daily slot.

    Riding on the heartbeat rather than a server-side cron is what makes the
    catch-up work: a device that was offline at its slot is still past it when
    it returns, and scans on the first heartbeat after that."""
    if not settings.patch_scan_enabled:
        return
    if not patch_scan.is_due(device_id, last_scan_at, settings.patch_scan_hour):
        return
    # Never while an install is running: the scan would report the half-patched
    # state and the install's own report overwrites it moments later anyway.
    if await jobs.active_job_of_kind(device_id, "patch_install") is not None:
        return
    patch_scan.mark_requested(device_id)
    await ws.send_json({"type": "patch_scan"})
    await audit_record("patch.scan_requested", actor="automation", device_id=device_id, daily=True)
    log.info("patch.scan_scheduled", device_id=device_id)


@router.websocket("/ws")
async def agent_ws(ws: WebSocket, settings: Settings = Depends(get_settings)) -> None:
    creds = _parse_bearer(ws.headers.get("authorization", ""))
    device = await devices.authenticate_device(*creds) if creds else None

    # Accept first, then close with an explicit code — rejecting during the
    # handshake surfaces as an opaque HTTP error in most WS clients.
    await ws.accept()
    if device is None:
        await ws.close(code=WS_CLOSE_UNAUTHORIZED, reason="invalid device credentials")
        return

    device_id = device["id"]
    was_connected = manager.is_connected(device_id)
    stale = manager.register(device_id, ws)
    if stale is not None:
        try:
            await stale.close(code=1000, reason="superseded by new connection")
        except Exception as e:  # noqa: BLE001 - any transport error is terminal here
            # The superseded socket is usually already dead; it has been
            # replaced in the registry regardless, so this only gets logged.
            log.debug("agent.stale_close_failed", device_id=device_id, error=str(e))
    if not was_connected:
        fleet_hub.broadcast("device_online")

    update_offered = False
    # Tracked per connection so the daily scan check costs no query per
    # heartbeat; the report handler below keeps it current.
    last_scan_at = int(device.get("last_patch_scan_at") or 0)
    try:
        while True:
            try:
                msg = await ws.receive_json()
            except ValueError:
                log.warning("agent.bad_json", device_id=device_id)
                await ws.close(code=1003, reason="invalid JSON")
                return
            if not isinstance(msg, dict):
                continue
            msg_type = msg.get("type", "")
            payload = msg.get("payload")

            if msg_type == "heartbeat" and isinstance(payload, dict):
                await devices.record_heartbeat(device_id, payload)
                await _maybe_request_patch_scan(ws, device_id, last_scan_at, settings)
                # Offer a signed update once per connection if this agent is
                # behind the current release. The agent verifies the signature
                # before installing, so this is a hint, not a trusted push.
                if not update_offered:
                    update_offered = True
                    upd = releases.update_for(
                        str(payload.get("agent_version", "")) or device["agent_version"],
                        device["os"],
                        device["arch"],
                    )
                    if upd is not None:
                        await ws.send_json({"type": "update", "payload": upd})
                        log.info("agent.update_offered", device_id=device_id, version=upd["version"])
                await metrics.record(
                    device_id,
                    cpu_pct=_as_pct(payload.get("cpu_pct")),
                    mem_pct=_as_pct(payload.get("mem_pct")),
                    disk_max_pct=max(
                        (
                            _as_pct(d.get("used_pct"))
                            for d in payload.get("disks") or []
                            if isinstance(d, dict)
                        ),
                        default=0.0,
                    ),
                )
            elif msg_type == "inventory" and isinstance(payload, dict):
                for kind in devices.INVENTORY_KINDS:
                    if kind in payload:
                        await devices.set_inventory(device_id, kind, payload[kind])
            elif msg_type == "job_started" and isinstance(payload, dict):
                job_id = payload.get("job_id")
                if isinstance(job_id, int):
                    await jobs.mark_running(job_id)
            elif msg_type == "job_output" and isinstance(payload, dict):
                job_id = payload.get("job_id")
                chunk = payload.get("chunk")
                if isinstance(job_id, int) and isinstance(chunk, str):
                    # ##RMM-CRED##-Zeilen abfangen, bevor sie in DB oder
                    # Live-Stream landen — Secrets gehören in den Tresor,
                    # nicht ins Job-Log. Ein Agent kann nur Credentials
                    # seines eigenen Geräts anlegen (device_id vom Socket).
                    clean, found = job_secrets.extract(job_id, chunk)
                    if found:
                        await job_secrets.store(device_id, job_id, found)
                    if clean:
                        await jobs.append_output(job_id, clean)
            elif msg_type == "job_result" and isinstance(payload, dict):
                job_id = payload.get("job_id")
                result_status = payload.get("status")
                exit_code = payload.get("exit_code")
                if isinstance(job_id, int) and isinstance(result_status, str):
                    # Zurückgehaltenes Zeilen-Fragment (Marker ohne
                    # abschließenden Umbruch) noch verarbeiten.
                    clean, found = job_secrets.flush(job_id)
                    if found:
                        await job_secrets.store(device_id, job_id, found)
                    if clean:
                        await jobs.append_output(job_id, clean)
                    await jobs.finish_job(
                        job_id,
                        result_status,
                        exit_code if isinstance(exit_code, int) else None,
                    )
            elif msg_type == "patch_report" and isinstance(payload, dict):
                items = payload.get("patches")
                if isinstance(items, list):
                    await patches.apply_scan(device_id, items)
                    last_scan_at = int(time.time())
                    await devices.mark_patch_scan(device_id, last_scan_at)
                    fleet_hub.broadcast("patches")
            elif msg_type == "agent_logs" and isinstance(payload, dict):
                lines = payload.get("lines")
                manager.resolve_logs(
                    device_id, [str(x) for x in lines] if isinstance(lines, list) else []
                )
            elif msg_type == "ping":
                # Lets agents (and tests) confirm the pipeline end-to-end:
                # everything sent before the ping has been processed.
                await ws.send_json({"type": "pong"})
            elif msg_type == "pong":
                pass
            else:
                log.info("agent.unknown_message", device_id=device_id, msg_type=msg_type)
    except WebSocketDisconnect:
        pass
    finally:
        manager.unregister(device_id, ws)
        if not manager.is_connected(device_id):
            fleet_hub.broadcast("device_offline")
